### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by nickvourd** [yutianqaq/Supernova_CN#1]
Do you want to add them in my original repo? I would appreciate it :)

**Comment by yutianqaq** [comment]
Sure, expect it to be done this week (as the code structure needs to be organized)

**Comment by nickvourd** [comment]
Thanks 🙏I appreciate your effort! When you finished open a pull request and I will review it next week! ❤️ if you have twitter add me and ping me there to talk about the tool more privately! Twitter: @nickvourd

**Comment by yutianqaq** [comment]
I'm currently unable to send direct messages on Twitter. However, you can reach me there by following this link: https://twitter.com/y2qaq. Please feel free to let me know your thoughts on the tool. Thank you!
